### PR TITLE
Add support for extending props and components.

### PR DESCRIPTION
**Pull request by alansouzati**
This is a PR to propose extending Props and Components.

It also allows for dynamicProps that when defined will receive the AST as a callback where you can define your dynamic properties.

### CODE REVIEW

**Comment by yaycmyk** [comment]
Thanks for submitting this! I'm going to do a riff on your idea tomorrow, good foundation.

**Comment by yaycmyk** [comment]
This support will be added via https://github.com/yaycmyk/markdown-to-jsx/pull/6, thanks!

**Comment by alansouzati** [comment]
Thanks! How about support for dynamicProps ?

For example, 

```
### Heading
```

I would like to be rendered as

```
<Heading tag='h3' />
```

**Comment by yaycmyk** [comment]
You'd have to enumerate each level in the override

**Comment by alansouzati** [comment]
Awesome, makes fully sense! thanks man! :+1:

**Pull request closed without merging**
